### ISSUE TITLE
Warning message formatting and text changes for empty-column-input.xlsx

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#225]
I've begun to run manual tests on the files in the test-files directory in order to review warning and error messages.

Right off the bat, I tried the file empty-column-input.xlsx and got a warning message.  I noticed a few things about this that need to be tweaked. 
* The current text of the warning is this:  There were 22 warning(s) detected in this file.  It is possible that these warnings are the result of extraneous data outside of the matrix, but we recommend you review your file and ensure that everything looks correct.  The graph will be loaded, but may not look the way it is expected to look.  To view the details of the warning(s), please select the dropdown below.
 * Please replace with this: There were 22 warning(s) detected in this file.  It is possible that these warnings are the result of extraneous data outside of the adjacency matrix, but we recommend you review your file to ensure that it is formatted correctly.  The graph will be loaded, but may not be displayed accurately.  To view the details of the warning(s), please click on the "Warnings List" link below.
* This particular file has 22 warnings.  However, when I click on the "Warnings List" link, I can only see 13 of them.  The window needs to have a scroll bar or some other mechanism for viewing the additional warnings that don't fit in the expanded window.
* The first warning: "A source gene was detected as NaN in column 6." does not conform to our decision to give cell references in Excel format, so this cell would be G1.  Instead of saying that it is detected as NaN, which is weird since it wouldn't be a number anyway, say that "A source gene name is missing from cell G1".
* The next 12 warnings are like this:  "The value in cell G2, was detected as being undefined."  Could it simply say that "The value in cell G2 is undefined."

**Comment by kdahlquist** [comment]
@anuvarsh just changed the text of the message, but the scrolling has not been fixed yet.

The missing source gene part is also in progress.

**Comment by anuvarsh** [comment]
The text for the missing source gene and missing target gene warnings have been fixed.

**Comment by anuvarsh** [comment]
In order to create a scroll bar, I will to create a div that contains the panel dictating the warnings list, and limit the height of that div. At that point, I should adjust overflow via css. 

The divs for the warning module are around line 170 in .upload.jade

**Comment by anuvarsh** [comment]
In changing some of the warning messages, the unit tests for 'extra-row-end-of-sheet-input.xlsx' and 'extra-row-end-of-sheet-output.xlsx' are no longer working. Will need to go back and fix that.

**Comment by anuvarsh** [comment]
The scroll bar has been implemented, however I'm not sure if I put the CSS in the right place. Will need to ask about this during the meeting.

All unit tests are currently passing, but when I manually checked 'extra-row-end-of-sheet-output.xlsx' I got the following warning message:
![image](https://cloud.githubusercontent.com/assets/8509674/10360318/a815c326-6d54-11e5-8e02-480083fa8cd5.png)

I'm not sure what happened I manually checked this sheet when I created it this summer, and since we do not currently have any unit tests written for warnings, this wasn't caught at least the school year started. In this sheet, there are a few random numbers placed at the very last row (row 1048576) of the sheet. I checked other extra-row sheets and a similar problem occurs but to a much lesser extent. For example, extra-row-one-row-skipped-output.xlsx returned the following warning message:
![image](https://cloud.githubusercontent.com/assets/8509674/10360745/d106d510-6d57-11e5-8eb6-272619fb122b.png)

No such issues exist for the extra-column sheets.

**Comment by kdahlquist** [comment]
We plan to collapse the warning messages so that if there are more than 3 warnings, the user sees the first 3 in full and then the message "and x more warnings like this".

**Comment by anuvarsh** [comment]
We want to make the warning modal to match the size of the screen. In order to do this we want to check the window height and then manually set the max height to be a reasonable difference based on the window height, but not any smaller than a minimum height in the case that the window is too small. 

This might we need to make a new div class and use an id to easily access the jquery. 

Read the bootstrap section on modals (getbootstrap.com). There is section within that talking about how the modal opens and how to insert some code before it opens. The actual code will be jquery. Any jquery tutorial will be helpful here.

**Comment by anuvarsh** [comment]
The code to make warning modal adjust to screen size has been pushed!

Working on consolidating the warnings in the warnings list.

**Comment by kdahlquist** [comment]
When the changes are live on the beta server then we should test the size of the modal window on multiple screens.

**Comment by kdahlquist** [comment]
The changes are live on the server, so I'm reassigning it to @kdahlquist.

**Comment by anuvarsh** [comment]
The warnings list now only shows the first 3 instances of the same type of warning, as well as a line that indicates how many more warnings of that type are left in the warnings array. This code has been pushed to beta.

**Comment by anuvarsh** [comment]
All of the updates made to the warnings list (collapsing if more than 3 of same warning appear and adjusting the size of the warning box according to screen size) seem to have been lost when we merged with the refactoring branch. Will need redo these updates.

**Comment by anuvarsh** [comment]
The scrolling has been fixed.

**Comment by kdahlquist** [comment]
I triggered a Warning as part of my testing for #312 and saw that this old text was still present:

"To view the details of the warning(s), please click on the "Warnings List" link below."

which should have been changed to

" To view the details of the warning(s), please click on the "Warnings List" link below."

This issue is so old, it is possible that it was changed on a different branch than what we are now working on, but I thought I should note this comment.

**Comment by kdahlquist** [comment]
I'm going to close this because I'm just not going to get to this.  I'm labeling it with "backlog" to indicate I'll come back to it if I have time.
