### ISSUE TITLE
Slider Display Values do not change after loading a file

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#364]
The slider values on beta stop updating once you load a file. Before loading, they work just fine, but after, the display values don't change, though the slider still has an effect on the graph.

**Comment by NAnguiano** [comment]
I've noticed that this actually has broken undo reset. Reset works, but undo reset is no longer functional on beta.

**Comment by NAnguiano** [comment]
This is still an issue. I don't feel comfortable with a master release (#422) unless this is fixed, as this is a pretty major bug with our force graph. I'll assign this to myself for now, but if anyone else wants to take it over and get it done, they can do it if they want.

**Comment by NAnguiano** [comment]
@ebachoura @eileenchoe I'm assigning this to the two of you. I'm also upping this to priority 0. This is too big of a bug in my opinion to ignore in a release.

**Comment by eileenchoe** [comment]
@ebachoura @NAnguiano and @eileenchoe collaborated on this issue and it is now fixed. Issuing the pull request now.

**Comment by kdahlquist** [comment]
I'm sorry to say that this is not completely fixed.  The slider values do change before I load a network.  However, once I load one of the demo's, the values no longer change when I move the sliders.  It looks like the opposite is happening from what @NAnguiano originally reported.

I tested both on Firefox and Chrome with beta v2.0.7.

**Comment by NAnguiano** [comment]
@kdahlquist Beta hadn't been updated with the most recent pull request that contained this fix, which is why it didn't seem to be working. It's updated now.

**Comment by kdahlquist** [comment]
Ah.  I refreshed and can see that it's fixed.  Closing.
