### ISSUE TITLE
Missing Value Error is not being caught when there are missing values in the matrix

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#417]
If there are any missing values in the matrix, a missing value error should be returned. Right now, a missing value error is not being returned. It also seems like the missing value error is being caught in the wrong spot - almost as if it's a catch-all for all of the problems that could arise in the matrix. In the spot that it looks like a missing value error should be caught, it seems as though an invalidMatrixData warning is being returned instead. However, in all missing value test files, there are no errors or warnings being returned at all.

**Comment by NAnguiano** [comment]
@eileenchoe @ebachoura, pinging you guys for this one.

**Comment by kdahlquist** [comment]
@eileenchoe, since you are in a stable state with #362, focus on fixing this bug first.

**Comment by NAnguiano** [comment]
I'm not sure if this is related to this or not, but I managed to get this error to show up while testing pull request #458. I loaded file adjacency-matrix-modifications > extra-column-end-of-sheet-input.xlsx.

![screen shot 2017-04-27 at 7 53 48 pm](https://cloud.githubusercontent.com/assets/6444156/25512536/6308e35a-2b83-11e7-9a74-0819e6a3c939.png)

This isn't a huge bug, but "undefined2" doesn't make much sense.

**Comment by anuvarsh** [comment]
Errors and warnings present the letter and number of the row and column. It looks like it's only catching the number and not the letter.

**Comment by NAnguiano** [comment]
@eileenchoe Weirdness is going on with the test suite. There's an error in the errors array that is straight up just half finished and doesn't actually seem to be used anywhere. It's called "outsideCellError". I'm worried that this testing problem may run a bit deeper than it appears even now...

![screen shot 2017-04-28 at 5 48 31 pm](https://cloud.githubusercontent.com/assets/6444156/25551526/eb92a00a-2c3a-11e7-8eab-f1271dc2ea60.png)
.... I have no idea how this happened, but git blame attributes it to me, so I suppose I have no one to blame but myself :scream:

**Comment by NAnguiano** [comment]
@eileenchoe I found more test weirdness! Namely this little gem in warnings-adjacency-matrix-modifications...
![screen shot 2017-05-02 at 5 12 28 pm](https://cloud.githubusercontent.com/assets/6444156/25644433/c0b5b00c-2f5a-11e7-9c8d-6a258f058476.png)

These are all missing column errors. Two return a warning. One doesn't. Since these are all missing in the matrix, I'd be inclined to say that all of these should return missing value errors.

**Comment by NAnguiano** [comment]
Hey @anuvarsh remember when we were refactoring the test suite and then we left for the summer and came back and realized that massive portions of the suite had somehow just disappeared into the abyss. And then this happened multiple times over the course of the semester we spent trying to fix it. And you and I never wanted to look at tests again after we thought it was fixed?

All I have to say is that I have no words at this point. 
![screen shot 2017-05-02 at 5 18 28 pm](https://cloud.githubusercontent.com/assets/6444156/25644524/a7ff1ade-2f5b-11e7-8a7a-e5a78a7fe4ac.png)

**Comment by NAnguiano** [comment]
I'm in the process of adding ESLint to our code.. And I actually found out that the "missing value errors" tests that are being done right now? They've been catching the fact that we've had a typo in our code for who knows how long in spreadsheet controller.

![screen shot 2017-05-15 at 1 15 51 am](https://cloud.githubusercontent.com/assets/6444156/26048452/12873fa8-390c-11e7-89cc-ce384432cfe8.png)

This errorsList variable? It doesn't exist. The variable is called "errorList", not errorsList.  So it throws an exception. That exception is caught by the try-catch, and returns the missing value error... which is currently the error that's returned when something goes wrong.

Even better, when I fixed the typo I found out... errorList had no warningsCountError property. The errorList in semantic checker had one, but not here. So, I added one. On the bright side, the test that says it should be returning a warnings count error is actually returning a warnings count error now. A whole 49,062 of them. It should realistically only return one of them, but eh. At least it's returning the right error now.

I'm like 10 files in with ESLint and  I've found so much of this weird stuff already. Most of it having to do with typos. Or functions being called that don't exist/variables being referenced that were never defined.

It's been a wild ride so far. I've just finished the server folder and I feel like this was long overdue.

**Comment by kdahlquist** [comment]
@eileenchoe, can you give a status update on this issue?  Is it fixed with PR #492 or are there still open tasks for this issue?

**Comment by eileenchoe** [comment]
I have not done work on this one. It was referenced in PR #492 because some tests related to this issue got messed up with the linting merge.

**Comment by kdahlquist** [comment]
OK, thanks for the update.

**Comment by kdahlquist** [comment]
Elevating the priority on this since the zoom work is finished.

**Comment by eileenchoe** [comment]
I began testing all the files in the adjacency-matrix-modifications and the warnings/errors dialogues are either not being triggered, or not displaying the wrong warning or error based on what I expect when looking at the spreadsheet. So as @NAnguiano suggested, this problem goes deeper than just the missing value error. These aren't being caught in the unit tests because the tests were written to expect no errors when it should be expecting errors, so refactoring will also have to be done to errors-adjacency-matrix-modifications and warnings-adjacency-matrix-modification files. 

I've identified a few things happening in spreadsheet controller that may be causing these issues and I have a good idea about how it needs to be fixed. I've read over the formatting guidelines in the Documentation to start, but I also want to confirm our formatting expectations for Excel inputs because this will require some larger changes with how we are parsing the spreadsheet.

**Comment by kdahlquist** [comment]
Lowering priority on this; @eileenchoe will you make sure to post notes on this before you leave for the summer?

**Comment by eileenchoe** [comment]
Yes! I'm actually going to write up a separate issue for this because the scope of this issue has widened to a review of the error and warning reporting in spreadsheet controller and corresponding unit tests.

**Comment by kdahlquist** [comment]
@afiller1, it seems like you have touched this issue.  Has your work resolved this?  I'm elevating it because this might be addressed by your work.

**Comment by dondi** [comment]
This might already be addressed by @Onariaginosa’s latest work and either way this part of the code is fresh in her mind so she will look into it to verify its status then report back.

**Comment by Onariaginosa** [comment]
This issue still occurs. @Onariaginosa's latest work deals with parsing expression sheets, and catches errors, including missing values in the various expression sheets. This issue seems to be with parsing the Network sheet. It will load an excel workbook that has a network sheet with no data, or missing data without a warning or an error.

**Comment by dondi** [comment]
All bugs in the import/export area remain a continuing high priority, so @Onariaginosa will forge ahead with this bug, moving on to testing the Network sheets now and seeking to apply the same robustness as the Expression Data sheets.

**Comment by Onariaginosa** [comment]
I tried restructuring the `parseNetworkSheet()` function in the Spreadsheet Controller to resemble `expression_sheet_parser.js`. I ended up with 155 errors, at the end of that process. so I am going to revert it back to the original and try again later.

**Comment by dondi** [comment]
@Onariaginosa clarified that the test failures were test assertion failures and not code (syntax/semantic) errors. Thus it's the behavior of the code that changed and the restructuring per se was the right thing to do but needs to be done in such a way that preserves the behavior of the code.

Suggestion for @Onariaginosa is to try to restructure in more granular steps, running the test suite in between. That way, changes in behavior can be caught sooner and can be re-examined more closely.

(P.S. The granular steps aren't always linear; it's good to maintain a bird's eye view at all times)

**Comment by Onariaginosa** [comment]
@Onariaginosa moved the `parseNetworkSheet()` function from _spreadsheet-controller.js_ into new file _network-sheet-parser.js_, and began the refactoring and restructuring process on the `parseNetworkSheet()` function. Currently, all tests continue to pass, and uploaded excel workbooks, display properly.

**Comment by dondi** [comment]
Looks like things are generally going well. It was recommended that @Onariaginosa also do an “eyeball/audit” of the existing test-data files to make sure that they indeed represent the errors that the filenames imply and it turns out that she has already been doing that.

@Onariaginosa can just continue on this path and will consult @dondi as needed if technical issues show up.

**Comment by Onariaginosa** [comment]
I added the cell A1 network warning, then refactored the test-files that brought errors with that change. While I was doing this, I noticed the there was a set of input/output test files `extra-column-end-of-sheet-input.xls`(or output) that appeared to be fine, but in their tests, it was expected that they would ultimately collect 49062 errors exactly, after processing, but now it returns 0 errors. I'm not sure how this was passing before, but it seems to be incorrect.

Additionally, when I add a new warning (error works fine) it does not appear in the warning box. It says there are 3 warnings, but it only displays 2. However when I change the warningCode to an existing warning it displays properly. This is depicted in the attached screenshots. I tried tracking where the warningCodes are referenced but it did not lead to any fruition. 

Additionally, I made the decision to not restructure the original Network sheet parser code because with one change, over 100 prior tests begin to fail, and debugging that takes up to hours each time. So I decide to work within the original, functioning code to add appropriate error checking.

![Screenshot from 2020-10-23 08-59-04](https://user-images.githubusercontent.com/21343072/97026630-7f09b480-150e-11eb-94f7-938f9dad19cd.png)
![Screenshot from 2020-10-23 01-46-59](https://user-images.githubusercontent.com/21343072/97026657-892bb300-150e-11eb-9f39-d2f021c7c83f.png)

**Comment by dondi** [comment]
The network parser refactoring issue has been moved to #890 and the new-warning issue is #892.

**Comment by Onariaginosa** [comment]
Originally there were 2 tests: `EmptyColumnError` and ` EmptyRowError`. However `EmptyRowError` only caught whether a row was completely empty, including the target gene name, and the `EmptyColumnError` was not implemented. @Onariaginosa started on `EmptyColumnError` and created 3 additional tests to catch missing values in the matrix. They are currently all works in progress:
     1. `EmptyColumnDataError`: when the column is empty, but the source gene still exists.
     2. `EmptyRowDataError`: when the row is empty, but the target gene still exists.
     3. `EmptyMatrixDataError`: when the adjacency matrix is empty, but the source and target genes are still there (Original Error reported)

**Comment by Onariaginosa** [comment]
I separated `EmptyRowDataError` and `EmptyMatrixDataError` from this issue into #417 because they are implemented in pull request #895. 
Tests `EmptyColumnError` and `EmptyColumnDataError` are mostly implemented. However they don't pass for some edge cases.

**Comment by dondi** [comment]
@Onariaginosa will finish tests for the remaining edge cases and upon that iteration, we may be able to close this issue.

**Comment by Onariaginosa** [comment]
@Onariaginosa fixed this bug in its entirety it will be implemented in a pull request.

**Comment by dondi** [comment]
@ahmad00m to add notes.

**Comment by ahmad00m** [comment]
I tested the new implemented tests for the adjacency matrix from the file exported from master branch/ test-files / demo-files / 21-genes_31-edges_schade-data_input.xlsx and the errors that GRNsight returned were accurate with the data missing in network sheet of excel file. This means the new implemented tests give accurate errors.
