### ISSUE TITLE
Going to the Beta page of GRNsight causes a Uncaught DOMException

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#455]
![image](https://cloud.githubusercontent.com/assets/8509674/25255772/6792ea12-25e1-11e7-8c5b-e582c13a2745.png)

This error appeared in the console when I opened the Beta page. The demo files are still loading.

**Comment by yshin4** [comment]
I'm not sure if it is caused by the same reason, but I also get a error when I try to upload any files to the graph.

![image](https://cloud.githubusercontent.com/assets/16246811/25551066/56dfcb0a-2c34-11e7-9976-34cbaf1cd221.png)

**Comment by NAnguiano** [comment]
Since @anuvarsh reported getting the same error that @yshin4 got above, I'm going to assign a Priority 0.5 to this. I haven't been able to reproduce it myself, but it does seem that it's not an isolated case.

**Comment by anuvarsh** [comment]
For reference: a new clone of my repo of GRNsight at commit 0c4103842eab29fc9d44e5ebd39c3a6f44eb3b11 caused this bug on my machine. The last version that I can confirm did not cause this problem was right before Nicole's first commit, which was commit 5f84b1a6ad793a592def2475a2da00f443f07ba2.

**Comment by NAnguiano** [comment]
@anuvarsh I did a fresh pull of your branch and found a bug - unweighted graphs wouldn't load at all, but weighted graphs loaded perfectly fine. I pushed a fix for it, and now all graphs are working just fine. From what you said, it seems like nothing at all would load, but if you can get a chance, take a look and see if that helped. I don't think this is related to @yshin4's bug though, unless she'd pulled your fork into hers. 

The current live beta is working for me both locally and on the website.

**Comment by anuvarsh** [comment]
@NAnguiano reported that she is able to run my GRNsight repo but I am still getting this problem: 
![image](https://cloud.githubusercontent.com/assets/8509674/25648205/508a5b2e-2f7e-11e7-99b1-168861534882.png)

No idea what is causing the problem. Nothing is showing up in the server that indicates an error, but I just can't upload anything. I also checked all dependencies and all of them are installed at the same version as our documentation and package.json indicates. I tried Chrome, Firefox, and Safari and I'm getting the same problem everywhere. This is mostly just disappointing because it is majorly stalling progress on #264

**Comment by kdahlquist** [comment]
Murphy's law always kicks in when there is a deadline.  Logic suggests that even though you both seem to have everything installed identically, there is actually some non-identical component causing the behavior.

If we had the resources, I would hand you an entirely different computer to use to see if we could get around the roadblock without having to track down the source of the problem.  But, of course, that's not really possible.

I'm sorry, I don't know what else to say.

**Comment by anuvarsh** [comment]
Actually, going to go ahead and say there is something going on in my machine. Despite doing a fresh clone of my repo (and then of @NAnguiano's) and trying to run GRNsight on both beta and master from both of our clones, I can't get anything to upload. At least we know it most likely isn't the code!

**Comment by kdahlquist** [comment]
Yeah.  I just don't have a substitute handy.  There are lots of extra Windows boxes I can get my hands on, but not Macs, unfortunately, and I don't want to open that can of worms anyway...(is there a worm emoji?)

**Comment by NAnguiano** [comment]
@yshin4 and @anuvarsh  have one thing in common - the issue both started after pulling beta. 

I think this is the ghost of GRNsight throwing a fit because it doesn't want me to leave.

**Comment by anuvarsh** [comment]
Either that, or GRNsight is trying to dump me.

**Comment by kdahlquist** [comment]
Before you guys get too maudlin, think about the complexity of what you all are doing right now.  There are six developers all working on different interdependent threads right now--these things are bound to happen!  When I was in grad school, I spent a good 9 months trying to get a particular experiment to work, doing it over again day after day after day before I finally got it to work.  This is what science is like!

**Comment by NAnguiano** [comment]
Ahh, science. Equal parts hard work, frustration, and satisfaction. Well, and reproducible research. I've roped two others into trying to install the latest code and report what happens for them. For now, I'm going to keep working

**Comment by kdahlquist** [comment]
Yes, @NAnguiano, onwards and upwards!

**Comment by dondi** [comment]
@anuvarsh and/or @yshin4 —if this is still happening on your computer and you have the time, bring it around to me if I’m in the office. I anticipate being there Wednesday afternoon.

**Comment by anuvarsh** [comment]
Yes yes, will do. I finish my final at 1 so I'll head over right after.

**Comment by dondi** [comment]
@anuvarsh and @dondi started looking at this today and the initial cause is that @anuvarsh was running GRNsight in the “old” way and as a result the paths to the demo files were incorrect.

@anuvarsh was running it the pre-`npm start` way because she couldn’t get it to work. @dondi tried an `npm install` after which it worked.

**Comment by dondi** [comment]
So I would consider this issue to be resolved. If it ever happens again, do the following:
- Delete all `node_modules` folders within the GRNsight folder
- Run `npm install`
- Use `npm start` from now on

With this we can close this issue.

**Comment by kdahlquist** [comment]
I will note more specifically that there was an old version of node-xlsx lurking on @anuvarsh's machine that was apparently causing the conflict.
