### ISSUE TITLE
Node coloring data options not cleared when loading a new file without expression data

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#777]
If I load demo 2 that has expression data, then I load demo 3 or 4 that don't have expression data, the sidebar menu is still displayed with the options for demo 2, i.e., it doesn't get cleared out when the new graph is loaded.  I can select the options (check/uncheck average box, etc.). Nothing happens to the graph, of course, but this stuff should go away when the next graph is loaded.

**Comment by kdahlquist** [comment]
Actually, this is a problem no matter what workbook you add next. If you load a workbook with expression data second, it is still showing the options for the previous one.

**Comment by dondi** [comment]
Sorry, I was unable to get to this one tonight. Maybe this can be one last thing for @mihirsamdarshi to address? This appears to be a matter of implementing more _update-app.js_ calls that update the state of the user interface based on the selected graph layout. The `updatetoForceGraph` and `updatetoGridLayout` functions appear to be the right places for making these adjustments.

**Comment by kdahlquist** [comment]
@mihirsamdarshi is going to work on this for the next hour to see if he can fix it today before the release.  If it can't be fixed by early afternoon (1:00 or 2:00), then we will save it for later.

**Comment by mihirsamdarshi** [comment]
This has been fixed in my branch

**Comment by kdahlquist** [comment]
Did beta really get refreshed?  If so, you forgot to bump the version number on the website.  Assuming what is up is really 3.1.24, I'm still seeing the bug.

**Comment by mihirsamdarshi** [comment]
yes, I forgot to push gh-pages

**Comment by kdahlquist** [comment]
OK, I reloaded, but I'm still seeing the bug.

**Comment by mihirsamdarshi** [comment]
Really? That is strange it is working for me on the website.

**Comment by dondi** [comment]
I can confirm that I can see the fix; @kdahlquist try clearing your browser cache or try out in Incognito/Private Mode first. The "regular" browser should eventually update too.

However, the http/https `server/ga?path=_____` error still gets blocked, it seems.

**Comment by kdahlquist** [comment]
OK, I completely closed and restarted the browser.  Let me be more specific as to what I see.

Going from demo 2 to demo 3 is fine.

However, going from demo 2 to demo 1 is not fine.  Demo 1 has _some_ expression data, but not all of what demo 2 has; demo 1 does not have the optimized_expression sheets.  However, the optimized expression choices are still in the drop down menus and when I select one of them, I get this:

![image](https://user-images.githubusercontent.com/6463867/59133316-6f46fb80-892c-11e9-9eed-4a8c5aa183ea.png)

**Comment by mihirsamdarshi** [comment]
I added a function called `clearDropdownMenus()`. Although added under the conditional `if (grnState.newNetwork)` it doesn't seem to clear the menus, despite the contents of the function working in the Chrome browser console.

**Comment by kdahlquist** [comment]
Average log fold change box states can stay; max log fold change value can stay, but the datasets need to be cleared.

**Comment by kdahlquist** [comment]
This is confirmed fixed on beta 4.0.1.
