### ISSUE TITLE
3-gene networks for six species to test gene page functionality

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#848]
To test the gene page feature, @Kevboe needs six test input workbooks that have genes for each of the species we support.  

I created one for Arabidopsis, which is attached here.  Use this template for each species, substituting genes.  

@kdahlquist is going to give 3 genes for each species.  @Kevboe needs to look up the expected results from each of the source databases

Arabidopsis:
* ABF1, JASPAR ID for this gene is MA0571.1
* BEE2, JASPAR ID for this gene is MA0956.1
* CBF1, JASPAR ID for this gene is MA1224.1

What I found already on beta 4.0.16 is that when I uploaded this network and chose Arabidopsis as species, since ABF1 is both a yeast gene and an Arabidopsis gene, a mix of yeast and Arabidopsis information was on the gene page.  Retrieval of SGD data needs to be disabled when a different species is selected.

[3-gene_7-edge_Arabidopsis.xlsx](https://github.com/dondi/GRNsight/files/4504999/3-gene_7-edge_Arabidopsis.xlsx)

**Comment by kdahlquist** [comment]
Human:
*  ATF3, JASPAR ID MA0605.2
*  BACH2, JASPAR ID MA1101.1
*  CDX2, JASPAR ID MA0465.1









Mouse:

Fly:

C. elegans:

**Comment by kdahlquist** [comment]
Mouse:
* Arid3a, JASPAR ID MA0151.1
* Bhlha15, JASPAR ID MA0607.1
* Creb5, JASPAR ID MA0840.1

Worm:
* atf-7, JASPAR ID MA1438.1
* blmp-1, JASPAR ID MA0537.1
* cebp-1, JASPAR ID MA1444.1

Fly:
* Antp, JASPAR ID MA0166.1
* br, JASPAR ID MA0010.1
* CG11085, JASPAR ID MA0171.1

It would be great to see some results of this testing in a PR sometime soon.  We are in a sprint to the finish to get this fully tested and rolled out in the next 2 weeks.

**Comment by Kevboe** [comment]
I created all of the workbooks and started testing, which took a while to find all of the genes and compare what was expected with what was returned. I found out a few important things that I think have priority to be fixed. First is that Ensembl doesn't seem to carry Arabidopsis data. Second is that there were still "too many requests" error from NCBI, but it seemed to return the expected data all but once (Melanogaster, br). Another error I received across the board, barring yeast and a portion of Arabidopsis, was that  Jaspar was not able parse any of the received data. I didn't see any errors in console regarding Jaspar, and saw that it was being passed in the correct ID, but I need to do more digging see why it was broken and to make sure that it all works. The final thing that I encountered seemed to be an interesting bug, which I am reporting here, but might need to make a separate issue for. When I was testing the C. elegans data, I found that the gene pages are not able to parse "-" in the node names. I can remake the workbook with different genes, but wasn't able to because of other homework. We can talk about direction and problem priorities tomorrow.

**Comment by kdahlquist** [comment]
Ensembl breaks plants out into a different site: http://plants.ensembl.org/index.html instead of the main Ensembl site.

**Comment by dondi** [comment]
For the “too many requests” error, @Kevboe can use a combination of the Network debug tool and some console logging to determine when/where the multiple requests are being sent.

For the species/query disconnects, verify that the parameters being sent are indeed the right ones either via documentation check or direct testing, e.g., with curl or Postman.

Finally, we will need to add more data to our "species dictionary" to direct the code in terms of where to contact the API (as with plants for Ensembl). This approach will also help us accommodate different MODs.

**Comment by kdahlquist** [comment]
@kevboe, are the test Excel files committed somewhere in the repository?  I'm not finding them easily.  I'd like to try them myself and see what happens.  Can you at least post them in this issue if they are not there?

**Comment by Kevboe** [comment]
I didn't commit them yet, but plan to. Here are the files that I am using to test.
[kev-fake-data-thaliana-full (1).xlsx](https://github.com/dondi/GRNsight/files/4549240/kev-fake-data-thaliana-full.1.xlsx)
[kev-fake-data-elegans-full (1).xlsx](https://github.com/dondi/GRNsight/files/4549241/kev-fake-data-elegans-full.1.xlsx)
[kev-fake-data-musculus-full (1).xlsx](https://github.com/dondi/GRNsight/files/4549242/kev-fake-data-musculus-full.1.xlsx)
[kev-fake-data-melanogaster-full.xlsx](https://github.com/dondi/GRNsight/files/4549243/kev-fake-data-melanogaster-full.xlsx)
[kev-fake-data-sapiens-full.xlsx](https://github.com/dondi/GRNsight/files/4549244/kev-fake-data-sapiens-full.xlsx)
[kev-fake-data-elegans-taxon-test.xlsx](https://github.com/dondi/GRNsight/files/4549247/kev-fake-data-elegans-taxon-test.xlsx)
[kev-fake-data-no-species.xlsx](https://github.com/dondi/GRNsight/files/4549248/kev-fake-data-no-species.xlsx)
[kev-fake-data-bad-species.xlsx](https://github.com/dondi/GRNsight/files/4549249/kev-fake-data-bad-species.xlsx)

**Comment by kdahlquist** [comment]
Notes from when I tested the "kev-fake-data-bad-species.xlsx" file.

1. I was going to suggest a different wording for the warning message, but now GRNsight beta appears to be crashed and I can't get the warning to display again.

2. What I was going to add is that we are defaulting to yeast if no species is chosen or if we don't recognize the species.  So, after you load this file and right-click a gene, the gene page should attempt to find yeast data and the species in the right-hand corner of the gene page should read yeast.

I can't go any further until @dondi  restarts GRNsight beta. (I don't know if anyone else can do it).

**Comment by kdahlquist** [comment]
I made a C. elegans file with just the C-elegans genes in the "network" sheet.  
[3-gene_7-edge_elegans.xlsx](https://github.com/dondi/GRNsight/files/4553284/3-gene_7-edge_elegans.xlsx)

I selected "C. elegans" as a species from the menu and loaded the file.  I right-clicked on "cebp-1"
- NCBI Gene ID was retrieved correctly
- Ensembl ID was not retrieved correctly because it was looking for yeast, not C elegans: https://uswest.ensembl.org/Saccharomyces_cerevisiae/Gene/Summary?g=CELE_D1005.3
- JASPAR not found
- UniProt not found

**Comment by kdahlquist** [comment]
file with only the "network" sheet for Drosophila with 3 genes and selecting Drosophila from the menu:
For CG11805 gene, 
* NCBI retrieved correctly
* Ensembl not retrieved correctly: https://uswest.ensembl.org/Saccharomyces_cerevisiae/Gene/Summary?g=Dmel_CG11085
* UniProt retrieved correctly
* JASPAR not found
[3-gene_7-edge_melanogaster.xlsx](https://github.com/dondi/GRNsight/files/4553311/3-gene_7-edge_melanogaster.xlsx)

For br gene
* NCBI link to wrong gene: https://www.ncbi.nlm.nih.gov/gene/34009 instead of https://www.ncbi.nlm.nih.gov/gene/44505
* Ensembl same problem
* UniProt correct
* JASPAR not found

For Antp gene
* NCBI correct
* Ensembl same problem
* UniProt not correct
* JASPAR not found

**Comment by kdahlquist** [comment]
Mouse: 
[3-gene_7-edge_musculus.xlsx](https://github.com/dondi/GRNsight/files/4553395/3-gene_7-edge_musculus.xlsx)

Creb5:
* NCBI found correctly
* Ensembl has same problem
* JASPAR not found
* UniProt link is only quasi-correct.  The link takes you to: https://www.uniprot.org/uniprot/A0A0N4SUK5, but it should really take you to: https://www.uniprot.org/uniprot/Q8K1L0

For Arid3a, same as above except UniProt should go to: https://www.uniprot.org/uniprot/Q62431

Bhlha15 should go to for UniProt: https://www.uniprot.org/uniprot/Q9QYC3

**Comment by kdahlquist** [comment]
Human: 
[3-gene_7-edge_sapiens.xlsx](https://github.com/dondi/GRNsight/files/4553421/3-gene_7-edge_sapiens.xlsx)

Behaving like mouse.

I'm not sure how the UniProt records are being found, but it seems that GRNsight is not choosing the canonical "reviewed" UniProt record for a gene, but instead is choosing a "TrEMBL" link instead.  TrEMBL links are redundant and not reviewed and aren't the ones we should be finding.

**Comment by Kevboe** [comment]
Notes about some of the errors that you have received, which I discovered after testing:
*Jaspar was having trouble returning because of the order in which the APIs were queried. I was able to remedy this in my API branch by swapping the order, but there is still more testing to be done. 
*Ensembl is not returning the proper data because it was hard coded to link to "https://www.ensembl.org/Saccharomyces_cerevisiae/Gene/Summary?g=" with the gene tag added on. I am not sure why this was done, or how easy of a fix it will be, because it seems like we are only linking to it, and not querying an  API
*In terms of the links linking to the "right but wrong" gene, I don't understand the difference on a technical level, and don't have enough information as to why it would pick one over the other. I can try to see if this is an issue that is fixable, but my priority is on making the other API calls work and making sure that yeastmine/GO don't throw errors if we are not in yeast.

**Comment by kdahlquist** [comment]
For bullet point 2 in the previous comment, it looks like this was overlooked when we "unhardcoded" everything from yeast.  It seems like you need to dynamically construct this URL, plugging in the right species from the one that is selected.  

Something like this would need to be done anyway because Arabidopsis needs to point to the plant. ensembl.org anyway.

For bullet point 3, there is probably a way to fix this in the API, but I don't know how the API is actually working, so if you can tell me the query to UniProt, I might be able to answer.

**Comment by Kevboe** [comment]
When we create the link it is adding the uniprot ID to a base uniprot link. It looks like it gets the uniprotID from what is returned, so the solution to this would be to somehow change our API query to make sure that we get back the proper one. Just don't know how to do this.

**Comment by Kevboe** [comment]
here is the data that we are passing in to the Uniprot API call. 
 data: {
            from: "GENENAME",
            to: "ACC",
            format: "tab",
            taxon: taxon,
            query: geneSymbol,
        },
The taxon is the id that is coded in when the user uploads their data, and the geneSymbol is whatever gene was clicked on.

**Comment by Kevboe** [comment]
Working on a fix for both the plants ensembl as well as the yeastmine/GO problems, and I ran into a weird error. It appears as if plants.ensembl is not nearly as well stocked with data as the normal ensembl is. I can't find ABF1 for A.thaliana. However I was able to get it to link to the base ensembl and plant ensembl depending on what species was selected.

**Comment by Kevboe** [comment]
Interesting bug, might need @dondi 's help to solve it. We are currently generating the Ensembl link from the locus tag that NCBI returns, but it doesn't always return it for other species, which makes generating the link difficult. For example ATF3 for Homo sapiens https://www.ncbi.nlm.nih.gov/gene/467 does not have a locus tag, but does have the desired information/link to ensembl under see related. Compare it to ZAP1 https://www.ncbi.nlm.nih.gov/gene/853390 for yeast. Furthermore if you look at A. thaliana it has the locus tag, but for Araport, (https://www.ncbi.nlm.nih.gov/gene/841395) which seems to be ensembl plant's place for storing all of the data for A. thaliana.

**Comment by kdahlquist** [comment]
There are a lot of individual issues mentioned in the comments to this one.  It would be useful to know which ones are resolved and which are still outstanding.  Anything still outstanding should be broken out into their own issues.  I made a 3-gene_7-edge test file for each of the species--are they committed to the repository yet?

**Comment by Kevboe** [comment]
Committing Dr. Dahlquist's files in test-files/species-test-data as well as removing old, no longer working files.

**Comment by Kevboe** [comment]
In terms of individual issues. The issues in my previous comment, quoted here, are still not resolved.

> Interesting bug, might need @dondi 's help to solve it. We are currently generating the Ensembl link from the locus tag that NCBI returns, but it doesn't always return it for other species, which makes generating the link difficult. For example ATF3 for Homo sapiens https://www.ncbi.nlm.nih.gov/gene/467 does not have a locus tag, but does have the desired information/link to ensembl under see related. Compare it to ZAP1 https://www.ncbi.nlm.nih.gov/gene/853390 for yeast. Furthermore if you look at A. thaliana it has the locus tag, but for Araport, (https://www.ncbi.nlm.nih.gov/gene/841395) which seems to be ensembl plant's place for storing all of the data for A. thaliana.

**Comment by kdahlquist** [comment]
backlogging all gene page issues
